#!/bin/bash

# Allow script to be ran only from MacOS systems
if [[ "$OSTYPE" != "darwin"* ]]; then
  echo "Installation is only supported on MacOS systems"
  echo "Exiting..."
  exit
fi

# shellcheck disable=SC2164
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd "${SCRIPT_PATH}"

# Install project
docker-compose up -d
docker-compose exec php composer install
docker-compose exec php ./vendor/bin/pimcore-install --admin-username admin --admin-password admin --mysql-username pimcore --mysql-password pimcore --mysql-database pimcore --mysql-host-socket db  --no-interaction
docker-compose exec php ./bin/console cache:clear